# Generated by Django 3.2.8 on 2021-10-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainId', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('srcId', models.TextField()),
                ('metric_1', models.FloatField()),
                ('metric_2', models.FloatField()),
            ],
        ),
    ]
