# Generated by Django 3.2.8 on 2021-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='mainId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
